#!/bin/sh
subdirs="svcore svgui svapp sonic-visualiser"
echo 
echo " *** Preparing to configure in: $subdirs"
echo
for dir in $subdirs; do
    echo " *** Configuring in: $dir"
    echo
    ( cd "$dir" && ./configure "$@" ) || exit 1
    echo
done
cat > Makefile <<EOF
TARGETS = sub-svcore sub-svgui sub-svapp sub-sonic-visualiser
sub-svcore:
	\$(MAKE) --directory=svcore
sub-svgui:
	\$(MAKE) --directory=svgui
sub-svapp:
	\$(MAKE) --directory=svapp
sub-sonic-visualiser:
	\$(MAKE) --directory=sonic-visualiser
EOF
echo " *** Generated Makefile"
