#!/bin/sh
port=`lsof -c sonic- | grep UDP | sed -e 's/^.*[^0-9]\([0-9][0-9]*\) *$/\1/' | grep -v ' ' | head -1`
if [ -z "$port" ]; then
    echo "Sonic Visualiser OSC port not found"
    exit 1
fi
if [ -n "$1" ]; then
    command=$1; shift
    echo "osc.udp://127.0.0.1:$port/$command" "$@"
    sv-osc-send "osc.udp://127.0.0.1:$port/$command" "$@"
else
    while read command arg1 arg2 arg3 arg4 arg5; do
	echo "osc.udp://127.0.0.1:$port/$command" $arg1 $arg2 $arg3 $arg4 $arg5
	sv-osc-send "osc.udp://127.0.0.1:$port/$command" $arg1 $arg2 $arg3 $arg4 $arg5
    done
fi

