FROM ubuntu:18.04
MAINTAINER Chris Cannam <cannam@all-day-breakfast.com>
RUN apt-get update && \
    apt-get install -y \
    software-properties-common \
    build-essential \
    libbz2-dev \
    libfftw3-dev \
    libfishsound1-dev \
    libid3tag0-dev \
    liblo-dev \
    liblrdf0-dev \
    libmad0-dev \
    liboggz2-dev \
    libopus-dev \
    libopusfile-dev \
    libpulse-dev \
    libasound2-dev \
    libjack-dev \
    libsamplerate-dev \
    libsndfile-dev \
    libsord-dev \
    libxml2-utils \
    libgl1-mesa-dev \
    raptor2-utils \
    git \
    mercurial \
    curl wget unzip \
    mlton \
    python3-pip \
    autoconf automake libtool lintian

# NB we do not install portaudio. We don't want to end up including it
# in the bundle, because it comes with a dependency on the JACK
# library which we don't want to bundle and can't assume people will
# have. However, we do install JACK because the Dynamic JACK mechanism
# should ensure we can detect, configure, and use that without
# actually linking against it. We also have Pulse as the default I/O.

RUN apt-add-repository -y ppa:beineri/opt-qt-5.15.2-bionic
RUN apt-get update && \
    apt-get install -y \
    qt515base \
    qt515svg
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git config --global http.postBuffer 4M

RUN git clone https://github.com/sandstorm-io/capnproto
WORKDIR capnproto
RUN git checkout v0.6.1
WORKDIR c++
RUN autoreconf -i && ./configure && make -j3 && make install

WORKDIR /root
RUN pip3 install meson

RUN wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
RUN unzip ninja-linux.zip
RUN ln -s $(pwd)/ninja /usr/bin/ninja

RUN wget https://breakfastquay.com/files/releases/rubberband-3.1.1.tar.bz2
RUN tar xvjf rubberband-3.1.1.tar.bz2
WORKDIR rubberband-3.1.1
RUN meson build -Ddefault_library=static && ninja -C build && ninja -C build install
WORKDIR /root

COPY id_rsa_build .ssh/id_rsa_build
COPY known_hosts .ssh/known_hosts
RUN chmod 600 .ssh/id_rsa_build .ssh/known_hosts
RUN echo '{"accounts": {"sourcehut": "~breakfastquay"}}' > .repoint.json
RUN ( echo '[ui]' ; echo 'ssh = ssh -i /root/.ssh/id_rsa_build' ) > .hgrc

# The explicit revision number here is to make sure the following git
# clone is not cached from a different revision
RUN echo Cloning revision [[REVISION]]

RUN git clone https://github.com/sonic-visualiser/sonic-visualiser
WORKDIR sonic-visualiser
RUN git checkout [[REVISION]]

ENV QTDIR /opt/qt515
ENV PATH /opt/qt515/bin:$PATH
ENV LD_LIBRARY_PATH /opt/qt515/lib/x86_64-linux-gnu:/opt/qt515/lib:$LD_LIBRARY_PATH
RUN cat /opt/qt515/bin/qt515-env.sh

RUN ./repoint install
RUN meson build --buildtype release
RUN ninja -C build

RUN deploy/linux/deploy-appimage.sh
RUN tar cvf output-appimage.tar *.AppImage && cp output-appimage.tar /tmp/
